name: Deploy Subdomain
on:
  push:
    branches:
      - main
    paths:
      - 'link/**'

permissions:
  contents: write # <--- Add this block

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Subdomain Branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: link
          branch: gh-pages-link
          token: ${{ secrets.GITHUB_TOKEN }} # <--- Ensure this is included